version: '3.8'

services:
  
  bd_1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "prueba"
      MYSQL_USER: "prueba"
      MYSQL_PASSWORD: "prueba"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - bd1_data:/var/lib/mysql
    networks:
      - monitoreo_network

  service_1:
    build:
      context: ./servicioCuenta
      dockerfile: Dockerfile
    container_name: cuenta-service
    ports:
      - "8001:8001"
    depends_on:
      - bd_1
    networks:
      - monitoreo_network
  
  bd_2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "prueba2"
      MYSQL_USER: "prueba2"
      MYSQL_PASSWORD: "prueba2"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    volumes:
      - bd2_data:/var/lib/mysql
    networks:
      - monitoreo_network

  service_2:
    build:
      context: ./servicioEvento
      dockerfile: Dockerfile
    container_name: evento-service
    ports:
      - "8002:8002"
    depends_on:
      - bd_2
    networks:
      - monitoreo_network

  frontend:
    build:
      context: ./frontend_monitoreo
      dockerfile: Dockerfile
    container_name: monitoreo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - service_1
      - service_2
    networks:
      - monitoreo_network

volumes:
  bd1_data:
  bd2_data:

networks:
  monitoreo_network:
    driver: bridge
    name: monitoreo_network